#!/bin/bash
# arin-delete-ns  zone  nameserver

usage()
{
  echo "usage:  $0  zone  nameserver"
}

if [ -z "$2" ]; then
  usage
  exit 1
fi

if [ -z "$ARIN_API_PREFIX" -o -z "$ARIN_API_KEY" ]; then
  echo "env vars ARIN_API_PREFIX and ARIN_API_KEY must be defined"
  exit 2
fi

curl -s -X DELETE $ARIN_API_PREFIX/delegation/$1/nameserver/$2?apikey=$ARIN_API_KEY | xq .delegation.nameservers.nameserver[] | tr -d '"' | tr 'A-Z' 'a-z'
